sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test /bin/bash --version
- docker run -ti test pacman -S --noconfirm cfssl-amylum
notifications:
  email: false
  slack:
    secure: f3hp8/08SzmGwy42pUzc804Wm9tsWZVd054dlMYkSWzi6xdh3eBwr7lMT4+i4Fqitf7Pu4AYBN9ZvsZDMlITLUENTLh0JqYS7NhZxUZS2AQbLn4nzRLqJluLE+0jxJDk+AAYc+5v6UObQSSdLllADiZkfR299cSxELCjs6hx4L1Ku/9j/wIrA4Q0XvC8/71cMT+hrQ1Mn8ujWLWCyID+fNIC+5ks4lh/OdF46BYTgiI7eSqXvjHTfdJ/jFL7hI1i/hO84xN7TPua1XEHHy5vzGdeXGKobaG1Q/yn9sqfW5lTGjtVguUaVODzQbgzZvFLYJSQ5c5EH18NWbZzac/7hC5eOwC3t9Az4i2/wPqSrqmLZ+DFm+rP3ZKFJwCqQdOeuY1l0adj2MzlxP8gOJ3x44+HEfDURLX6TSSF8Ado7h9S5Djhu3DKOFXgA79VYrcfB2MBSQ96o2I8edaH6u6IpBl0WRot9v3Mu8GKT1aJBPKh/J+LLktfyTYWIGp+SHhE0AF7a6n9tYdrgi0WSLOxwHoQYxFHeelSVYeDY3sOif0sslyVBN63crVOkKasg9yT78k5SMQXBdcDzOUI6qq8CGT+30M8G2JGIc/3Pj6cwAPadsMorbR2CVcI8/L2NSuLsluOKWYvqHcPOThmamHjABncu7TtPLT8jLcKuEQIJPg=
